name = "solarportal"
main = "src/worker.js"
compatibility_date = "2024-09-26"
workers_dev = false

[[routes]]
pattern = "solarportal-server.alexgs.co.uk"
zone_name = "alexgs.co.uk"
custom_domain = true

[[d1_databases]]
binding = "solarportal"
database_id = "b0113c65-182e-4d1b-8401-e872f07b0be9"
database_name = "solarportal"
